import 'bootstrap/dist/css/bootstrap.css'

import Navbar from '@/components/navbar/Navbar'
import './scss/style.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sb-app">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
